<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TargetFrameworks>netstandard2.1;</TargetFrameworks>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\TritonInference.Binary\TritonInference.Binary.csproj" />
      <ProjectReference Include="..\..\src\TritonInference.Client.Grpc\TritonInference.Client.Grpc.csproj" />
    </ItemGroup>

</Project>
