<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TargetFrameworks>netstandard2.1;</TargetFrameworks>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TritonInference.Binary\TritonInference.Binary.csproj" />
    </ItemGroup>

</Project>
